Darwin x64 only
jitsi/jitsi-meet-electron-sdk pull request #210
Opened 2022-03-15 11:05 UTC by saghul

Otherwise projects not building for arm64 on macOS (yet) run into a build problem because the prebuild cannot be found.

2022-03-15 21:46 UTC, csett86 requested changes
In general I agree to the approach, but from my testing the x64-only would be taken preferred to the universal build prebuild. Have you tested this on Darwin arm64 that there the universal prebuild is still preferred over the x64 one?

On a separate note: does the npm audit fix have to be part of this?

2022-03-15 21:46 UTC, csett86 commented on .gitignore
> +prebuilds/
This was on purpose not on the .gitignore, as otherwise npm package will also ignore it when uploading to npm.

Thus please revert

2022-03-15 22:29 UTC, saghul commented
I don't have access to an M1 mac, so I'm flying blind here, alas.

The audit fix is unrelated I just ran into it when I did npm install.

2022-03-15 22:36 UTC, csett86 commented
While thinking about it, can you elaborate a bit more on the build errors that you are seeing? As the universal build for jitsi-meet-electron is internally also 2 single arch builds, and they work fine with the current prebuilds:

   • rebuilding native dependencies  dependencies=@jitsi/electron-sdk@3.0.6, @jitsi/robotjs@0.6.8 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=17.1.2 appOutDir=dist/mac-universal--x64
  • downloading     url=https://github.com/electron/electron/releases/download/v17.1.2/electron-v17.1.2-darwin-x64.zip size=81 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v17.1.2/electron-v17.1.2-darwin-x64.zip duration=1.152s
  • rebuilding native dependencies  dependencies=@jitsi/electron-sdk@3.0.6, @jitsi/robotjs@0.6.8 platform=darwin arch=arm64
  • packaging       platform=darwin arch=arm64 electron=17.1.2 appOutDir=dist/mac-universal--arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v17.1.2/electron-v17.1.2-darwin-arm64.zip size=84 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v17.1.2/electron-v17.1.2-darwin-arm64.zip duration=1.261s
  • packaging       platform=darwin arch=universal electron=17.1.2 appOutDir=dist/mac-universal


Separately I just locally build x64 only for jitsi-meet-electron and I cannot reproduce any build failure with the released universal build version 3.0.6.

2022-03-16 20:40 UTC, csett86 commented
I tested and its at least not breaking M1 Macs, but before merging I would like to understand the issue and have the .gitignore and package-lock.json changes reverted.

2022-03-16 21:03 UTC, saghul commented
Here is the error we get:

<img width="1027" alt="electron build image" src="https://user-images.githubusercontent.com/317464/158690411-c5d5df06-8dd9-4d87-8af7-42f3384f3d77.png">



> and have the .gitignore and package-lock.json changes reverted.

Why though? It's a separate commit and I do want those changes in too.  Making a separate PR just to split the commit out is kinda pointless.

2022-03-16 21:17 UTC, csett86 commented
Thanks for the error message, I'll check this tomorrow.

> > and have the .gitignore and package-lock.json changes reverted.
> 
> Why though? It's a separate commit and I do want those changes in too. Making a separate PR just to split the commit out is kinda pointless.

We can keep the package-lock.json and then I won't squash merge.

But the .gitignore change breaks publishing the prebuilds to npm (as everything from .gitignore is also ignored during npm package), thus please revert that, otherwise we don't have any prebuilds in the published packages after this change.

2022-03-16 22:55 UTC, saghul commented
> But the .gitignore change breaks publishing the prebuilds to npm (as everything from .gitignore is also ignored during npm package), thus please revert that, otherwise we don't have any prebuilds in the published packages after this change.

Ah, gotcha, good point!

2022-03-16 22:57 UTC, saghul commented
Updated, reverted the .gitignore change.

2022-03-17 07:53 UTC, csett86 approved these changes

2022-03-17 08:07 UTC, merged

2022-03-17 11:43 UTC, csett86 commented
Would be interested if this release 3.0.7 now fixes your issue, as I could not reproduce the issue in any way with an x64 only build.

2022-03-17 12:47 UTC, saghul commented
I am not the one running into the problem, I did pass it to a colleague who was.